spring:
  data:
    mongodb:
      uri: mongodb://root:example@mongodb:27017/fraud-db?authSource=admin
  redis:
    host: redis
    port: 6379
    timeout: 10000
    connect-timeout: 10000
    retry:
      max-attempts: 3
      max-delay: 1000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

server:
  port: 8081